# Generated by Django 2.2.6 on 2019-11-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drivers',
            new_name='TarjetaVideos',
        ),
    ]
