# Generated by Django 2.2.6 on 2019-11-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191117_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=50)),
                ('usuario', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
