# Generated by Django 2.2.6 on 2019-11-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='contraseña',
            field=models.CharField(max_length=40, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.CharField(max_length=40, verbose_name='Usuario'),
        ),
    ]
